# Generated by Django 3.1.1 on 2020-09-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='max_salary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='min_salary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
