# Generated by Django 3.1.1 on 2020-09-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20200912_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.user'),
            preserve_default=False,
        ),
    ]
