# Generated by Django 3.1.1 on 2020-09-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_auto_20200912_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Position',
            new_name='position',
        ),
    ]
