# Generated by Django 3.1.1 on 2020-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_auto_20200912_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
